//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.7.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface UserAudit {
    auditChangeId: number;
    auditUserId: number;
    auditChangeDate: Date;
    auditChangeType: string | undefined;
    userId: number;
    userName: string | undefined;
    userMail: string | undefined;
    isActive: boolean | undefined;
    createdDate: Date | undefined;
    createdBy: number | undefined;
    modifiedDate: Date | undefined;
    modifiedBy: number | undefined;
    loginName: string | undefined;
    cultureCode: string | undefined;
    upi: string | undefined;
    ouId: number | undefined;
    title: string | undefined;
    hideProcessHistory: boolean | undefined;
    seeCompactView: boolean | undefined;
    loginFailedAttemptsCount: number | undefined;
    lastLoginAttempt: Date | undefined;
    hideAudit: boolean | undefined;
    division: string | undefined;
}