//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.7.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface UserRoleEntityAudit {
    auditChangeId: number;
    auditUserId: number;
    auditChangeDate: Date;
    auditChangeType: string | undefined;
    userId: number;
    roleId: number;
    entityId: number;
    createdDate: Date | undefined;
    createdBy: number | undefined;
    jobDescription: string | undefined;
}