//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.7.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface OrganizationalUnitAudit {
    auditChangeId: number;
    auditUserId: number;
    auditChangeDate: Date;
    auditChangeType: string | undefined;
    ouId: number;
    ouName: string | undefined;
    ouDescription: string | undefined;
    ouCode: string | undefined;
    createdDate: Date | undefined;
    createdBy: number | undefined;
    modifiedDate: Date | undefined;
    modifiedBy: number | undefined;
    isActive: boolean | undefined;
    ouParentId: number | undefined;
    ouTypeId: number | undefined;
    hasAdvisor: boolean | undefined;
    currencySymbol: string | undefined;
    rightSymbol: boolean | undefined;
    currencyId: number | undefined;
    ouCountryCode: string | undefined;
    departmentId: number | undefined;
    hasOdsSearch: boolean | undefined;
    hcoOds: boolean | undefined;
    hasLinkZinc: boolean | undefined;
    allowApprovalPrivateOrganization: boolean | undefined;
    showThirdPartyLogisticsVendorTab: boolean;
    inputCharactersRemaining: number | undefined;
    recipientEntityTypeId: number | undefined;
    allowHcoInProfessionalServices: boolean;
    allowSupportGroupSubmitForms: boolean | undefined;
    blockBudgetReconciliation: boolean | undefined;
    allowSelectionAdvisorsDecisionMaker: boolean | undefined;
    removeAdvisorInSendBackInitiator: boolean | undefined;
    allowChangeAdvisorToDecisionMaker: boolean | undefined;
    countryWithCertification: boolean | undefined;
    rolesSyncWithAd: boolean | undefined;
    ntGroupName: string | undefined;
    onlyHasApprovalPhase: boolean | undefined;
    wbsSelectable: boolean | undefined;
    hasAttendeesExtended: boolean | undefined;
    hasSolicitedUnsolicited: boolean | undefined;
    hasProductProjectActivity: boolean | undefined;
    hasSearchSapProvider: boolean | undefined;
    infieldActivity: boolean | undefined;
    hasInternalOrders: boolean | undefined;
    allGenerateContract: boolean | undefined;
    hasRecipientsStatusTracking: boolean | undefined;
    hasSignedContracts: boolean | undefined;
    activateEventsModule: boolean | undefined;
    allowSupportGroupToCancelForms: boolean | undefined;
    selectLoadModeRecipientsDetails: boolean | undefined;
    isOdsLocal: boolean | undefined;
    isEnableDisableAutomaticContractingTool: boolean | undefined;
    additionalApprovalBeforeCloseout: boolean | undefined;
    isSapLocal: boolean | undefined;
    hasLogisticalArrangementsExtended: boolean | undefined;
    additionalApprovalBeforeCloseoutRolId: number | undefined;
    isOuAllergan: boolean | undefined;
    isCrossBorderHost: boolean | undefined;
    isCrossBorderHome: boolean | undefined;
    isCrossBorder: boolean | undefined;
    hasMassiveUploadAssistants: boolean | undefined;
    hasInvitationLettersAssistants: boolean | undefined;
    hasPsExtendedGeneric: boolean | undefined;
    hasLogisticalReconciliation: boolean | undefined;
    hasFinancialData: boolean | undefined;
    useMdm: boolean | undefined;
    hasAllerganContractTemplate: boolean | undefined;
}