//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.7.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface Login {
    domain: string | undefined;
    userName: string | undefined;
    loginName: string | undefined;
    password: string | undefined;
}