//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.7.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface OrganizationalUnit {
    ouId: number;
    ouName: string | undefined;
    ouDescription: string | undefined;
    ouCode: string | undefined;
    createdDate: Date;
    createdBy: number;
    modifiedDate: Date;
    modifiedBy: number;
    isActive: boolean;
    ouParentId: number | undefined;
    ouTypeId: number;
    hasAdvisor: boolean;
    currencySymbol: string | undefined;
    rightSymbol: boolean | undefined;
    currencyId: number | undefined;
    ouCountryCode: string | undefined;
    departmentId: number | undefined;
    hasOdsSearch: boolean;
    hcoOds: boolean;
    hasLinkZinc: boolean;
    allowApprovalPrivateOrganization: boolean;
    showThirdPartyLogisticsVendorTab: boolean;
    inputCharactersRemaining: number | undefined;
    recipientEntityTypeId: number | undefined;
    allowHcoInProfessionalServices: boolean;
    allowChangeAdvisorToDecisionMaker: boolean | undefined;
    allowSupportGroupSubmitForms: boolean;
    blockBudgetReconciliation: boolean;
    allowSelectionAdvisorsDecisionMaker: boolean;
    removeAdvisorInSendBackInitiator: boolean;
    countryWithCertification: boolean;
    rolesSyncWithAd: boolean;
    ntGroupName: string | undefined;
    onlyHasApprovalPhase: boolean | undefined;
    wbsSelectable: boolean;
    hasAttendeesExtended: boolean;
    hasSolicitedUnsolicited: boolean;
    hasProductProjectActivity: boolean;
    hasSearchSapProvider: boolean;
    infieldActivity: boolean;
    hasInternalOrders: boolean;
    allGenerateContract: boolean;
    hasRecipientsStatusTracking: boolean;
    hasSignedContracts: boolean;
    activateEventsModule: boolean;
    allowSupportGroupToCancelForms: boolean;
    selectLoadModeRecipientsDetails: boolean;
    isOdsLocal: boolean;
    isEnableDisableAutomaticContractingTool: boolean;
    additionalApprovalBeforeCloseout: boolean;
    isSapLocal: boolean;
    hasLogisticalArrangementsExtended: boolean;
    additionalApprovalBeforeCloseoutRolId: number | undefined;
    isOuAllergan: boolean;
    isCrossBorderHost: boolean;
    isCrossBorderHome: boolean;
    isCrossBorder: boolean;
    hasMassiveUploadAssistants: boolean;
    hasInvitationLettersAssistants: boolean;
    hasPsExtendedGeneric: boolean;
    hasLogisticalReconciliation: boolean;
    hasFinancialData: boolean;
    useMdm: boolean;
    hasAllerganContractTemplate: boolean;
    upLevel: number | undefined;
    path: string | undefined;
    ouCountryId: number | undefined;
}