//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.7.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface OrganizationalUnitHcoSapProvider {
    ouHcoSapProviderId: number;
    ouId: number;
    hcoCode: string | undefined;
    hcoName: string | undefined;
    sapProviderCode: string | undefined;
    sapProviderCodeId: string | undefined;
    sapProviderName: string | undefined;
    sapProviderAddress1: string | undefined;
    sapProviderAddress2: string | undefined;
    sapProviderAddress3: string | undefined;
    sapProviderAddress4: string | undefined;
    sapProviderCity: string | undefined;
    sapProviderCounty: string | undefined;
    sapProviderPostcode: string | undefined;
    hasDonations: boolean;
    inObservation: boolean;
    hasPatientsAssociation: boolean;
    typologyFmvId: number;
    statutesFileContentGuid: string | undefined;
    statutesFileName: string | undefined;
    isActive: boolean;
    createdBy: number;
    createdDate: Date;
    modifiedBy: number;
    modifiedDate: Date;
    sapProviderId: number | undefined;
    hcoAddress: string | undefined;
    hcoPostcode: string | undefined;
    hcoCity: string | undefined;
    hcoCif: string | undefined;
    fileSize: number | undefined;
}