//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.7.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface OrganizationalUnitEventTaxRange {
    taxRangeId: number;
    taxRangeFrom: number;
    taxRangeTo: number;
    taxRangeTax: number;
    ouId: number;
    createdDate: Date;
    createdBy: number;
    modifiedDate: Date;
    modifiedBy: number;
}