//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.7.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface OrganizationalUnitIncomeTax {
    incomeTaxId: number;
    ouId: number;
    incomeTaxClass: string | undefined;
    incomeTaxDescription: string | undefined;
    incomeTaxRetention: boolean;
    incomeTaxCode: string | undefined;
    incomeTaxDocDescription: string | undefined;
    incomeTaxCreateRegisters: boolean | undefined;
    incomeTaxVatIncludeVendors: boolean | undefined;
    incomeTaxActivityCode: boolean;
    incomeTaxIncomeValue: number;
    createdDate: Date;
    createdBy: number;
    modifiedDate: Date;
    modifiedBy: number;
}