//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.7.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface OrganizationalUnitIvaTax {
    ivaTaxId: number;
    ouId: number;
    ivaTaxType: string | undefined;
    ivaTaxApplicationType: boolean;
    ivaTaxDescription: string | undefined;
    ivaTaxClass: string | undefined;
    ivaTaxDeductible: boolean;
    ivaTaxForeigner: boolean;
    ivaTaxDeductibleForeigner: boolean;
    ivaTaxLedgerAccount: string | undefined;
    ivaTaxDistribution: string | undefined;
    ivaTaxActivityCode: boolean;
    ivaTaxIvaValue: number | undefined;
    ivaTaxMinAmount: number | undefined;
    ivaTaxMinRate: number | undefined;
    ivaTaxMaxRate: number | undefined;
    createdDate: Date;
    createdBy: number;
    modifiedDate: Date;
    modifiedBy: number;
}