//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.7.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface OrganizationalUnitContract {
    ouContractId: number;
    ouId: number;
    fullNameAbbvie: string | undefined;
    address: string | undefined;
    city: string | undefined;
    countryId: number;
    userName: string | undefined;
    otherInformation: string | undefined;
    userFunction: string | undefined;
    createdBy: number;
    createdDate: Date;
    modifiedBy: number;
    modifiedDate: Date;
}