//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.7.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface OrganizationalUnitTerritory {
    territoryId: number;
    ouCountryId: number;
    territoryParentId: number | undefined;
    territoryTypeId: number;
    territoyName: string | undefined;
    territoryCode: string | undefined;
    createdBy: number;
    createdDate: Date;
    modifiedBy: number;
    modifiedDate: Date;
}