//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.7.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface OrganizationalUnitTeam {
    ouId: number;
    teamId: number;
    createdBy: number;
    createdDate: Date;
    ouName: string | undefined;
    teamName: string | undefined;
    teamCode: string | undefined;
    teamNameComplete: string | undefined;
}