//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.7.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface OrganizationalUnitSigner {
    signerId: number;
    signerName: string | undefined;
    signerTitle: string | undefined;
    signerDni: string | undefined;
    ouId: number;
    isActive: boolean;
    createdDate: Date;
    createdBy: number;
    modifiedDate: Date;
    modifiedBy: number;
    signerEmail: string | undefined;
    isLegalRepresentative: boolean;
}