//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.7.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export enum PermissionId {
    Activities = 1,
    CreateMapFormsHome = 2,
    Searcher = 3,
    Dashboard = 4,
    BackofficeAdministration = 5,
    Delegations = 6,
    AdminUsers = 7,
    AdminOrganizationalUnits = 8,
    AdminMaintenance = 9,
    MyTasks = 10,
    AdminEvents = 11,
    AdminCustomers = 12,
    AdminDelegations = 13,
    AdminOds = 14,
    AdminDataExtraction = 15,
    AdminAuditTrail = 16,
    AdminProviders = 17,
    AdminCostCentersWbs = 18,
    AdminContracts = 19,
    AdminHcoSap = 20,
    AdminInternalOrders = 21,
    AdminLogs = 22,
    AdvancedSearch = 23,
    Events = 24,
    SecurityTracking = 25,
    Planea = 26,
    PlaneaGlobalAdminPlanea = 27,
    PlaneaSeeOnlyMyAccounts = 28,
    PlaneaSeeMedicalAmountsOnCommercial = 29,
    PlaneaTacticalPlansEdition = 30,
    PlaneaBudgetControlSeeAllBrands = 31,
    PlaneaAccountsConsultation = 32,
    PlaneaTacticalPlansConsultation = 33,
    PlaneaFixAnalysis = 34,
    PlaneaGlobalPlansAdmin = 35,
    PlaneaSipAccessWithoutMedicalDepartment = 36,
    PlaneaSipViewAllBrands = 37,
    PlaneaSipViewAllAccounts = 38,
    AdminTransparency = 39,
    CrossBorder = 40,
    AdminWaivers = 41,
    AdminMdm = 42,
}

export interface Permission {
    permissionId: PermissionId;
    permissionNameLocalizable: string | undefined;
    permissionDescription: string | undefined;
}