//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.7.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface ReferenceTableItem {
    itemId: number;
    itemNameLocalizable: string | undefined;
    itemCode: string | undefined;
    itemTypeId: number;
    isActive: boolean;
    createdBy: number;
    createdDate: Date;
    modifiedBy: number;
    modifiedDate: Date;
    itemOrder: number | undefined;
    itemTypeParentNameLocalizable: string | undefined;
    textId: number | undefined;
    nameLocalizable: string | undefined;
    textEn: string | undefined;
    textEs: string | undefined;
    textCs: string | undefined;
    textHu: string | undefined;
    textPl: string | undefined;
    textRo: string | undefined;
    textRu: string | undefined;
    textBg: string | undefined;
    textUk: string | undefined;
    textKk: string | undefined;
    textBe: string | undefined;
    textSk: string | undefined;
    textFr: string | undefined;
    textZh: string | undefined;
    textKo: string | undefined;
    textDe: string | undefined;
    textAt: string | undefined;
    textIt: string | undefined;
}