//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.7.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export enum UnauthorizedReason {
    None = 0,
    Unautenticated = 1,
    NoAppUser = 2,
    AccessDenied = 3,
}