//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.7.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface UserProperties {
    userId: number;
    userPasswordHash: string;
    userPasswordSalt: string;
    userPasswordExpirationDate: Date | undefined;
    userLoginAttemps: number | undefined;
    createdDate: Date;
    createdBy: number;
    modifiedDate: Date;
    modifiedBy: number;
    changePasswordUrlExpirationDate: Date | undefined;
    changePasswordUrlKey: string;
    loginName: string;
    userName: string;
    userEmail: string;
    isActive: boolean;
}