//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.7.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export enum RoleId {
    Initiator = 1,
    Advisor = 2,
    DecisionMaker = 3,
    Oec = 4,
    SupportGroup = 5,
    Viewer = 6,
    System = 7,
    AreaFunctionalAdmin = 8,
    AreaSecurityAdmin = 9,
    CountryFunctionalAdmin = 10,
    CountrySecurityAdmin = 11,
    GlobalFunctionalAdmin = 12,
    GlobalSecurityAdmin = 13,
    Notifier = 14,
    SecondAdvisor = 15,
    BusinessSupport = 16,
    Validator = 17,
    OecPlus = 18,
    Legal = 19,
    CountrySecurityLead = 20,
    PlaneaBusinessPlansUser = 21,
    PlaneaFinancialPlanning = 22,
    PlaneaConsultation = 23,
    PlaneaAdministrator = 24,
    ProductOwner = 25,
    CrossBorderAdmin = 26,
}

export interface UserRoleOrganizationalUnit {
    ouId: number;
    ouAreaId: number | undefined;
    ouParentId: number | undefined;
    ouParentName: string | undefined;
    ouName: string | undefined;
    ouTypeId: number;
    ouType: string | undefined;
    hasAdvisor: boolean;
    currency: string | undefined;
    userId: number;
    userName: string | undefined;
    loginName: string | undefined;
    upi: string | undefined;
    userMail: string | undefined;
    isActive: boolean;
    role: string | undefined;
    roleDescription: string | undefined;
    title: string | undefined;
    jobDescription: string | undefined;
    lastLoginAttempt: Date | undefined;
    ouIsActive: boolean;
    ouParentIsActive: boolean;
    ouParentBusinessUnitId: string | undefined;
    isOuAllergan: boolean;
    roleId: RoleId;
}