//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.7.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface MasterData {
    masterItemId: number;
    masterDataTypeId: number;
    masterItemName: string;
    masterItemDescription: string;
    createdDate: Date;
    createdBy: number;
    modifiedDate: Date;
    modifiedBy: number;
    isActive: boolean;
    ordinal: number | undefined;
    typeName: string;
    creatorName: string;
    modifierName: string;
}